name: ${pluginName}
version: ${version}
main: ${group}.${packageName}.plugin.${pluginName}Plugin
api-version: 1.20
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - org.jetbrains.kotlin:kotlin-reflect:1.8.21
  - io.github.monun:kommand:3.1.7
  - io.github.muqhc:runction:0.3.0